### ISSUE TITLE
Impossible to commit a whole directory

### ISSUE THREAD

**Issue by culot** [fenix-hub/godot-engine.github-integration#32]
When pressing "Select Directory" to commit a whole folder (around 6M in size), the output window says "blobbed each file with success, start committing..." and nothing else happens but a spinning wheel for more than 15 minutes.

**Comment by fenix-hub** [comment]
Hi,
Could you please provide me some more informations about the issue?
Godot version, Plugin version, some messages before the "blobbed each file with success", or simply a screenshot of the bug you are encountering.

Thank you very much.

**Comment by culot** [comment]
Sure, here are the versions:

Godot Engine v3.1.2.stable.official
GitHub Integration Version 0.7.8

The addon was installed from within Godot, via the AssetLib.
Unfortunately I removed the addon from my project so I could not provide you with a screenshot.
However, I suspect this might be related to the authentication method (login / password), which will soon be (or is?) deprecated, as mentionned here: https://developer.github.com/v3/auth/

**Comment by fenix-hub** [comment]
Thank you very much for these informations.

I'm currently working on a little update for the 3.2.x versions of Godot, since the second-last update (0.7.5) of my plugin had some bugs, and they propagated to the last version (0.7.8).

I'll release the new version as soon as possible, so (I hope) won't be any bug anymore. I'm still testing it on 3.1.2 and different 3.2 versions.

For your bug,
I don't think it has something to do with the authentication method, maybe it is just an in-code bug.

I'm aware of the authentication situation : the login/password will be deprecated soon, but my plugin has always worked with the mail / Token method too, so when the current authentication method will be deprecated you can just click on the button _Create Token(?)_ in the Sign-in interface, create your token and access. 
The authentication informations you send to access your GitHub profile are the same as the ones you use to work with your repos/gists on the plugin.

Anyway, the next version of this plugin will implement a mandatory mail/token method, even though the mail/password method is still supported in the meanwhile.

Since I won't update the plugin in the AssetLibrary until the 3.2 stable release, feel free to join the platforms where new updates are announced, or just follow this repo and you will receive the new version update. I'll reply to this issue anyway with the new update link.

Thank you again for the feedback and for using this plugin!

**Comment by fenix-hub** [comment]
Hi @culot ,
Hope #33 will fix things up. It's a preview for the next update
Just pull from [master](https://github.com/fenix-hub/godot-engine.github-integration) and let me know
