### ISSUE TITLE
Multiple plugins in the Godot Asset Library

### ISSUE THREAD

**Issue by SekoiaTree** [fenix-hub/godot-engine.github-integration#48]
There seems to be two identical plugins in the Godot asset library:
![image](https://user-images.githubusercontent.com/51149447/85206566-58026280-b323-11ea-8f32-bc94e24b7a1f.png)
![image](https://user-images.githubusercontent.com/51149447/85206575-6781ab80-b323-11ea-8c1b-29b790f88f0a.png)
![image](https://user-images.githubusercontent.com/51149447/85206581-6f415000-b323-11ea-834b-c06b1e098452.png)
I assume the later version is the correct one, but this could still provoke some confusion

**Comment by fenix-hub** [comment]
Hi @SekoiaTree ,
Thank you for bringing this up.
I'm afraid I'm not able to remove the plugin through the Asset Library.
Initially there were two plugins for two different versions, since the Asset Library was supposed to show a plugin only for the version of Godot you are using.
This feature has not been added, probably because the current Asset Library itself is not been updated.
I'll change the descrition of the latter version.
thanks
