### ISSUE TITLE
Cant download branch[Bug] 

### ISSUE THREAD

**Issue by BroBriek** [fenix-hub/godot-engine.github-integration#74]
**Godot Version & Plugin Version**
Godot: 3.2.1
Plugin: 0.1.5

**Describe the bug**
When trying to pull a project from a github branch it stops downloading and i get the following error:
 
core/io/http_client.cpp:591 - HTTP Chunk too big!! >16mb
 core/bind/core_bind.cpp:3220 - Error parsing JSON at line 0:

**Comment by fenix-hub** [comment]
Hi @BroBriek ,
It looks more like a Godot issue rather than an issue with the plugin itself.
The `core/io/http_client.cpp:591 - HTTP Chunk too big!! >16mb` makes me think that the problem could be pretty clear: the client is limiting the pull request because the zipped repository could be more than 16mb. 
I'll let this issue open in order to investiate more anyway.
Thank you for this!

**Comment by fenix-hub** [comment]
Related to https://github.com/godotengine/godot/issues/41882
