### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by BlockOG** [fenix-hub/godot-engine.github-integration#80]
**Godot Version & Plugin Version**
Godot: *3.2.3.stable.official*
Plugin: *1.3.4* and not wanting to update even through files

**Describe the bug**
I'm trying to log in I'm writing all of the details of my account and it doesn't work. It may be because I'm already logged in but then why doesn't it get me to the repository. And also I **can** look at my notifications and change my settings but I can't access the repositories.

**Screenshots**
![Issue_01](https://user-images.githubusercontent.com/68442822/101656200-1f7a5080-3a4b-11eb-9459-24464516e614.png)
![Issue_02](https://user-images.githubusercontent.com/68442822/101656206-2012e700-3a4b-11eb-9fbc-637ecca48842.png)

**OS**
*Linux Ubuntu 20.04.1 LTS*

**Comment by fenix-hub** [comment]
Hi @BlockOG ,
Have you ever logged successfully previously?
Are you using proper credential combination (email + **token**, not password)?
I see in the console "ERROR 3 : bad credentials"

Also, in order to avoid bugs like these, using the latest release is mandatory.
Updating your plugin won't make you lose any data, everything is store. Don't worry

**Comment by BlockOG** [comment]
I know that updating the plugin won't lose any data but I don't know how to update.
Yes I did log in successfully previously and I did put in the email and token not password, it's a bug that it shows 
"ERROR 3: bad credentials"

**Comment by fenix-hub** [comment]
To update the plugin, you can:
- Clone the repository and un-zip it inside the "addon" folder 
or (easier way)
- Look for "Github Integration" in the Asset Library inside Godot Engine's Editor and download the latest version
