### ISSUE TITLE
[Feature] Add password sign in

### ISSUE THREAD

**Issue by Shadowblitz16** [fenix-hub/godot-engine.github-integration#91]
**Describe the feature you'd like**
Add a way to sign in via password instead of token

**Describe a possible solution of implementation**
Let us pick whether we sign in by token or password by a drop down box or label button

**Additional context**
NA

**Comment by fenix-hub** [comment]
Hi,
Unfortunately there's no way to log using your password, since there is no real login. 
The token is required by Github to authenticate your requests and restrict the access of this plugin to the fields you only want to work with.
Anyway there's an automatic login option, and your mail/token is automatically stored, so you just have to insert them once.
After the first login just press the "sign in" button and it will automatically fill the fields.
